### ISSUE TITLE
Bug report: Slash-up should not fail silently if command argument description is too long

### ISSUE THREAD

**Issue by mount2010** [Snazzah/slash-up#55]
Steps to reproduce:
- Make a command with an argument description that is too long.
- Run slash-up local. 
- Note that slash-up doesn't list the command, even though it exists and is being compiled, and doesn't notify the user.

**Comment by Snazzah** [comment]
It shows warnings for when registering a command errors here, it's just behind the debug flag:
https://github.com/Snazzah/slash-up/blob/1547a531e1388e7e7002b69ce1795cdae8a07b0c/src/config.ts#L123-L124

Might just remove the debug flag check from it later though.
